Repository datalad/release-action, pull requests merged in 2022-10, with the labels that each got.

#13 Fix Git invocations
  datalad_release_action/__main__.py
Labels: patch

#16 Add type-checking
  .github/workflows/typing.yml
  datalad_release_action/client.py
  noxfile.py
  setup.cfg
Labels: tests

#11 Eat our own dogfood
  .datalad-release-action.yaml
  .github/workflows/add-changelog-snippet.yml
  .github/workflows/release.yml
  .github/workflows/update-tag.yml
  README.md
  changelog.d/scriv.ini
  changelog.d/templates/entry_title.md.j2
  changelog.d/templates/new_fragment.md.j2
  config.example.yml
  release/action.yml
Labels: major

#15 Add command for creating/updating labels
  README.md
  changelog.d/pr-15.md
  datalad_release_action/__main__.py
  datalad_release_action/client.py
  datalad_release_action/config.py
  noxfile.py
Labels: minor, release

#19 Fix handling of version tags that start with `v`
  changelog.d/pr-19.md
  datalad_release_action/versions.py
Labels: patch, release

#23 Improve handling of `tag-prefix` (now a config file option)
  .datalad-release-action.yaml
  .github/workflows/release.yml
  README.md
  changelog.d/pr-23.md
  datalad_release_action/__main__.py
  datalad_release_action/config.py
  datalad_release_action/util.py
  datalad_release_action/versions.py
  release/action.yml
Labels: major

#17 Add `populate-workflows.sh` script
  README.md
  changelog.d/pr-17.md
  populate-workflows.sh
Labels: minor

#24 Rename `fragment_directory` option to `fragment-directory`
  .datalad-release-action.yaml
  README.md
  changelog.d/pr-24.md
  datalad_release_action/config.py
Labels: major

#25 Properly update major version branch
  .github/workflows/release.yml
  .github/workflows/update-tag.yml
  changelog.d/pr-25.md
Labels: internal

#26 Make @GITHUBHANDLE into proper markdown hyperref
  changelog.d/pr-26.md
  changelog.d/templates/new_fragment.md.j2
Labels: documentation

#29 Make sample actions & workflows use `@v1`
  README.md
  changelog.d/pr-29.md
  populate-workflows.sh
Labels: documentation, release

#30 Fix "Update major version branch" step
  .github/workflows/release.yml
  changelog.d/pr-30.md
Labels: internal
